package cn.origin.cube.utils

const val PENCLI = "a"
const val FILE = "b"
const val FILES = "c"
const val STACK = "d"
const val TAG = "e"
const val TAGS = "f"
const val PUSHPIN = "g"
const val DATABASE = "h"
const val SEARCH = "i"
const val LOCK = "j"
const val UNLOCK = "k"
const val WRENCH = "l"
const val EQUALIZER = "m"
const val EQUALIZER2 = "n"
const val COG = "o"
const val COGS = "p"
const val MAGIC_WAND = "q"
const val METER = "r"
const val AIRPLANE = "s"
const val TARGET = "t"
const val POWER = "u"
const val MENU = "v"
const val EARTH = "w"
const val PAPERCLIP = "x"
const val EYE = "y"
const val BOOKMARK = "z"
const val BOOKMARKS = "A"
const val SUN = "B"
const val PLUS = "C"
const val MINUS = "D"
const val ERROR = "E"
const val ARROW_UP = "G"
const val ARROW_RIGHT = "H"
const val ARROW_DOWN = "I"
const val ARROW_LEFT = "J"
const val PARAGRAPH = "K"
const val CLOUD = "L"
const val STACK_OVER_FLOW = "M"


